# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elk_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Log',
            new_name='LogType',
        ),
        migrations.RenameField(
            model_name='logtype',
            old_name='type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='projectlog',
            old_name='logs',
            new_name='log_type',
        ),
    ]
