# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elk_app', '0002_auto_20170413_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardlink',
            name='user',
        ),
    ]
